// Developer Express Code Central Example:
// How to implement drag and drop between a scheduler and a grid
// 
// This example illustrates how to implement drag and drop for appointments between
// a SchedulerControl and a GridControl. Note that we handle the PreviewMouseDown
// and PreviewMouseMove events of the TableView Class
// (http://documentation.devexpress.com/#WPF/clsDevExpressXpfGridTableViewtopic) to
// initiate drag-and-drop operations for the GridControl (we use
// DragDrop.DoDragDrop Method
// (http://msdn.microsoft.com/en-us/library/system.windows.dragdrop.dodragdrop.aspx)
// for this purpose), whereas this operation is initiated automatically for the
// SchedulerControl (if the OptionsCustomization.AllowAppointmentDrag Property
// (http://documentation.devexpress.com/#WPF/DevExpressXpfSchedulerOptionsCustomization_AllowAppointmentDragtopic)
// has its default value). The PreviewDrop event of the TableView and
// SchedulerControl.AppointmentDrop Event
// (http://documentation.devexpress.com/#WPF/DevExpressXpfSchedulerSchedulerControl_AppointmentDroptopic)
// are handled to process SchedulerDragData dropped in the GridControl and
// SchedulerControl respectively.
// Note: Rows in the GridControl are dragged via
// the RowIndicatior (see the screenshot in the TableViewHitInfo Class
// (http://documentation.devexpress.com/#WPF/clsDevExpressXpfGridTableViewHitInfotopic)
// help section) in this example.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E3808

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerGridDragDrop.Properties {


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if ((resourceMan == null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchedulerGridDragDrop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
